FROM messense/rust-musl-cross:x86_64-musl as chef
ENV SQLX_OFFFLINE=true
RUN cargo install cargo-chef

WORKDIR /server

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /server/recipe.json recipe.json
RUN cargo chef cook --release --target x86_64-unknown-linux-musl --recipe-path recipe.json

COPY . .
RUN cargo build --release --target x86_64-unknown-linux-musl

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /

COPY --from=builder /server/target/x86_64-unknown-linux-musl/release/server /server

RUN chmod +x /server

ENTRYPOINT ["/server"]
EXPOSE 8080